allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
patchedDependencies:
  '@better-auth/oauth-provider@1.6.23': patches/@better-auth__oauth-provider@1.6.23.patch
