allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@ark-ui/solid@5.39.2'
  - lucide-solid@1.46.0
overrides:
  fast-uri: '>=3.1.6'
  deepmerge-ts: '>=8.0.0'
  mysql2: '>=3.23.1'

